set(macros
    "analyze a macros_1"
    "archi a macros_1"
    "arrows a macros_1"
    "compile a macros_1"
    "crown a macros_1"
    "basic3d a macros_1"
    "ellipse a macros_1"
    "eval a macros_1"
    "event a macros_1"
    "feynman a macros_1"
    "first a macros_1"
    "formula1 a macros_2"
    "framework a macros_2"
    "gaxis a macros_2"
    "gaxis3 a macros_2"
    "greyscale a macros_2"
)
