name: Test-Root-Graphic CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x]
        cxx: [g++-11, g++-12, g++-13]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Node.js dependencies
        run: npm install

      - name: Install C++ compiler ${{ matrix.cxx }}
        run: sudo apt-get install -y ${{ matrix.cxx }}

      - name: Install CMake
        run: sudo apt-get install -y cmake

      - name: Build project
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

      - name: Run tests with ctest
        run: |
          cd build
          ctest --output-on-failure
 