name: Test-Root-Graphic CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x]
        cxx: [g++-11, g++-12, g++-13]

    steps:
      - name: Install Node.js dependencies
        run: npm install

      - name: Set up C++ compiler (Ubuntu)
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ matrix.cxx }}
          sudo apt-get install -y xutils-dev libxi-dev libxxf86vm-dev x11proto-xf86vidmode-dev mesa-utils xvfb libgl1-mesa-dri libglapi-mesa libosmesa6 musl-dev libgl1-mesa-dev
          sudo apt-get install -y build-essential libxi-dev libglu1-mesa-dev libglew-dev pkg-config
          echo "CXX=${{ matrix.cxx }}" >> $GITHUB_ENV

      - name: Build Root-graphic test
        run: mkdir -p build

      - name: Configure and build project
        run: |
          cd build
          cmake ..
          make

      - name: Run my test
        run: |
          cd build
          ctest --parallel 9